name: iOS UI-tests

on:
  workflow_dispatch:
    inputs:
      testplan:
        required: true
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Smoke
      device:
        required: true
        default: 'iPhone 13'
        type: choice
        options:
          - 'iPhone 13'
          - 'iPhone 14'
          - 'iPhone 15'
          
env:
  LC_ALL: en_US.UTF-8
  LANG: en_US.UTF-8
  TESTPLAN: ${{ inputs.tesplan || 'Debug' }}
  DEVICE: ${{ inputs.device || 'iPhone 13' }}

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout git
        uses: actions/checkout@v3
      - name: Get info
        run: env
      - name: Clean old files
        run: |
          rm -rf ./DerivedData
          rm -rf ./Report
          rm -rf xcresults
      - name: Setup env
        run: |
          ruby -v
          bundle install
      - name: Build app
        run: fastlane ios build_calculator
      - name: Run tests
        run: fastlane ios test_app testplan:"${TESTPLAN}" device:"${DEVICE}"
      - name: Install xcresults
        if: ${{ always()}}
        run: |
          curl -OL https://github.com/eroshenkoam/xcresults/releases/latest/download/xcresults
          chmod +x xcresults
      - name: Convert to allure results
        if: ${{ always()}}
        run: |
          ./xcresults export ./Report/TurboCalculator.xcresult ./allure-results
      - name: Save allure results
        if: ${{ always()}}
        uses: actions/upload-artifact@v4.1.0
        with:
          name: Allure
          path: allure-results
          retention-days: 30
          
                  
      - name: summary
        run: echo "$(git show -s --format=%s)" >> "$GITHUB_STEP_SUMMARY"
        
